# Generated by Django 5.0 on 2024-03-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
