# Generated by Django 5.0 on 2024-03-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_comment", "0001_initial"),
        ("core_user", "0005_user_posts_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comment_liked",
            field=models.ManyToManyField(
                related_name="commented_by", to="core_comment.comment"
            ),
        ),
    ]
