# Generated by Django 5.0 on 2024-03-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0006_user_comment_liked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="comment_liked",
            new_name="comments_liked",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
